### ISSUE TITLE
Typescript error with "placeholder" property.

### ISSUE THREAD

**Issue by ornato-t** [metonym/svelte-search#18]
The `placeholder` property doesn't appear to be included in the [types file](https://github.com/metonym/svelte-search/blob/master/src/Search.svelte). As such, when using it I am getting the following Typescript error:

> Object literal may only specify known properties, and '"placeholder"' does not exist in type 'SearchProps'.ts(2353)

![immagine](https://github.com/metonym/svelte-search/assets/53061271/b4dd4100-63b7-4b57-99e6-d5128fac9942)

This is purely about dev-x and annoying red squiggly lines, of course the resulting code works just as expected, and the placeholder text is rendered properly when the search bar is empty.

**Comment by metonym** [comment]
Thank you for reporting this. It should very much be considered a bug.

This should be fixed in version [2.0.2](https://github.com/metonym/svelte-search/releases/tag/v2.0.2)

**Comment by ornato-t** [comment]
After updating to 2.0.2 I can confirm that it's indeed fixed, thanks for the quick response!

P.S. as a user of both your svelte-search and [svelte-typehead](https://github.com/metonym/svelte-typeahead) modules thank you SO much for building them. Game changers when building search features. Cheers!
